spring:
  datasource:
    url: jdbc:mysql://localhost:3306/landin_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: 33686dc8-4e53-4fc5-bd61-f5569551ea94
  expiration: 86400000
  refresh-expiration: 604800000