spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/landin_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: ${JWT_SECRET:33686dc8-4e53-4fc5-bd61-f5569551ea94}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

app:
  public-base-url: ${APP_PUBLIC_BASE_URL:http://localhost:8080}

blockchain:
  enabled: ${BLOCKCHAIN_ENABLED:false}
  skip-metadata-url-check: ${BLOCKCHAIN_SKIP_METADATA_URL_CHECK:false}
  minter-private-key: ${BLOCKCHAIN_MINTER_PRIVATE_KEY:}

fabric:
  enabled: true
  channel-name: channel1
  chaincode-name: visitledger
  msp-id: Org1MSP
  peer-endpoint: localhost:7051
  tls-cert-path: ${user.home}/Desktop/land-in/land-in/.landin-runtime/fabric-certs/tls-ca.crt
  user-cert-path: ${user.home}/Desktop/land-in/land-in/.landin-runtime/fabric-certs/user-cert.pem
  user-key-path: ${user.home}/Desktop/land-in/land-in/.landin-runtime/fabric-certs/user-key.pem
  deadline-seconds: 30
